tpch_medallion_multiplatform:
  target: snowflake
  
  outputs:
    snowflake:
      type: snowflake
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'TPCH_MEDALLION_DBT_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema: dev
      threads: 4
      query_tag: dbt_tpch_medallion_native
      
    databricks:
      type: databricks
      catalog: "{{ env_var('DATABRICKS_CATALOG', 'dev') }}"
      schema: tpch_medallion
      threads: 4